ShoppingListAddItem:
  action:
    - action: shell_command.assist_skills
      data:
        skill: shopping-list
        args:
          intent: AddItem
          item: "{{ item }}"
          listName: Test
          prefix: '🤖'
      response_variable: result
    - stop: ""
      response_variable: result
  speech:
    text: "{{ action_response.stdout }}"